name: Generate GitHub Stats Cards

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fez6/github-profile-summary-cards-example@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: howardpen9
          THEME: github_dark
